title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Well hello there! I'm a data analyst with experience in political science, digital marketing, media, 
  and journalism. I’m experienced with Python, SQL, and Excel.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/rafalzabinski/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
